from __future__ import annotations

from pydantic import BaseModel, Field


class AgentChatSource(BaseModel):
    """Metadata for a retrieved source chunk used by an agent answer."""

    document_id: str = Field(..., description="Identifier of the source document.")
    chunk_number: int = Field(..., description="Chunk sequence number used in the answer generation context.")
    similarity_score: float = Field(..., description="Similarity score of the retrieved source chunk.")


class AgentChatResponse(BaseModel):
    """Response returned by the agent-orchestrated chat endpoint."""

    session_id: str = Field(..., description="Conversation session identifier.")
    selected_agents: list[str] = Field(..., description="Agents selected by the orchestrator.")
    question: str = Field(..., description="Original user question.")
    answer: str = Field(..., description="Answer generated by the selected agent or merged from collaborating agents.")
    sources: list[AgentChatSource] = Field(default_factory=list, description="Source chunk metadata used to ground the answer.")
